ARG BUILD_FROM
FROM $BUILD_FROM

# Add env
ENV LANG=C.UTF-8
ENV SNAPCAST_VERSION=0.32.1-r0
ENV LIBRESPOT_COMMIT=78ce118d32912adfb2705481f69c83df6a88211f
ENV PATH="/root/.cargo/bin:${PATH}"
# --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main \
RUN \
    apk add --no-cache --virtual .build-dependencies \
    build-base \
    git \
    libc-dev \
    musl-dev \
    protobuf-dev \
    && cd /tmp \
    && curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && mkdir librespot \
    && cd librespot \
    && git init \
    && git remote add origin https://github.com/librespot-org/librespot.git \
    && git fetch --depth=1 origin 78ce118d32912adfb2705481f69c83df6a88211f \
    && git checkout FETCH_HEAD \
    && cargo build --release \
    --no-default-features \
    --features "with-libmdns rustls-tls-native-roots" \
    \
    && cp target/release/librespot /usr/bin/librespot \
    && cp target/release/librespot /librespot \
    && apk del --no-cache --purge .build-dependencies build-base git protobuf-dev musl-dev libc-dev  \
    && cd \
    && rm -fr \
    /tmp/* \
    ~/.cargo \
    /usr/.crates.toml \
    /usr/.crates2.json

#Install snapcast
RUN sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories \
    # && apk add --no-cache librespot=${LIBRESPOT_VERSION} --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing \
    && apk add --no-cache snapcast-server=${SNAPCAST_VERSION} bash --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main

# Copy data for add-on
COPY run.sh /
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]
